<?php


$productions = [
    new Movie('Comandante', 'Edoardo De Angelis', ['Pierfrancesco Favino', 'Massimiliano Rossi', 'Johan Heldenbergh'], ['Drammatico'], 'ITA', '01 Distribution', 'La storia di Salvatore Todaro, comandante di sommergibili della Regia Marina che durante la Seconda Guerra Mondiale contravvenne agli ordini del suo comando per portare in salvo i 26 uomini che avevano provato ad affondarlo.', new Media('Comandante.jpg', 'Film Comandante'), 2.1, '2023/08/30', '2h 00min'),

    new TvSerie('Mr. Robot', 'Sam Esmail', ['Rami Malek', 'Christian Slater', 'Carly Chaikin'], ['Poliziesco', 'Drammatico', 'Thriller'], 'USA', 'USA Network', 'Elliot Alderson è un giovane ingegnere informatico di New York che lavora come esperto di sicurezza informatica presso la Allsafe Cybersecurity.[6] Sociofobico, la sua mente è fortemente influenzata da deliri paranoici e allucinazioni che gli causano grossi problemi nel relazionarsi con le persone e che lo fanno vivere in un costante stato di ansia e paranoia. Nella vita privata, Elliot è uno stalker informatico che tratta le persone come computer da hackerare per scoprirne i segreti più intimi.', new Media('MrRobot.png', 'Tv Serie Mr. Robot'), 5, '2015/06/24', '2019/12/22', 46, 4),

    new Movie('Pulp Fiction', 'Quentin Tarantino', ['John travolta', 'Quentin Tarantino', 'Samuel L. Jackson', 'Uma Thurman', 'Harvey Keitel', 'Tim Roth', 'Bruce Willis', 'Rosanna Arquette'], ['Crime'], 'USA', '	Miramax Films', 'Una giovane coppia di rapinatori e amanti, "Zucchino" (Ringo) e "Coniglietta" (Yolanda), stanno architettando il loro prossimo colpo, quando, su iniziativa di lui, decidono di operare proprio nel locale in cui si trovano. Si alzano annunciando a gran voce l\'inizio della rapina e puntando le pistole.', new Media(null, 'Film Pulp Fiction'), 5, '1994/05/21', '2h 57min'),

    new Movie('Il grande Lebowski', 'Joel Coen, Ethan Coen', ['Jeff Bridges', 'John Goodman', 'Julianne Moore', 'John Turturro'], ['Commedia'], 'USA/GBR', 'Gramercy Pictures', '“Drugo” Lebowski (Bridges) è un uomo originale che vivacchia senza impegnarsi, dormendo, fumando moderatamente marijuana, giocando a bowling coi suoi fidati amici (Goodman e Bushemi). Un giorno due brutti ceffi gli sporcano un tappeto. È lo spunto della vicenda. Drugo finisce invischiato nella misteriosa scomparsa della giovane moglie di un ricco si chiama Lebowski anche lui con tanto di riscatto da pagare. Incontra un’artista d’avanguardia, matta, che gli fa fare una visita ai genitali, incrocia un giocatore di bowling che crede di essere dio (Turturro), un magnate della pornografia che disegna omini supercazzuti e una banda scalcinata che cerca di recuperare il riscatto.', new Media('Lebowsky.png', 'Film Il grande Lebowski'), 4.5, '1998/05/01', '1h 57min'),

    new TvSerie('Dexter', 'James Manos Jr.', ['Michael C. Hall', 'Jennifer Carpenter', 'David Zayas'], ['Poliziesco', 'Drammatico', 'Thriller'], 'USA', 'Showtime', 'Di giorno, Dexter è un analista sanguinario per la polizia di Miami. Ma di notte, è un serial killer che ha come bersaglio solo altri assassini.', new Media('DEX.jpg', 'Tv Serie Dexter'), 4.5, '2006/08/01', '2013/09/22', 96, 8),

    new Movie('Killers of the Flower Moon', 'Martin Scorsese', ['Leonardo di Caprio', 'Robert De Niro', 'Jesse Plemons'], ['Drammatico', 'Crime'], 'USA', 'Rai Cinema', 'Il film è un crime movie tratto dall’omonimo romanzo di David Grann che racconta l’indagine svolta dall’FBI su quanto accaduto in Oklaoma, nella contea di Osage agli inizi degli anni Venti. Parallelamente alla scoperta di giacimenti di petrolio nella zona, si sono verificati una serie di omicidi di cittadini della tribù indiana della contea.', new Media('Killers.jpg', 'Film Killers of the Flower Moon'), 4.2, '2023/10/19', '3h 26min'),

    new Movie('The Marvels', 'Nia DaCosta', ['Brie Larson', 'Zawe Ashton', 'Teyonah Parris'], ['Azione', 'Fantasy'], 'USA', 'The Walt Disney Company Italia', 'Il film è il sequel di Captain Marvel e vede l’eroina Carol Danvers / Captain Marvel fronteggiare una nuova minaccia, ma questa volta non sarà sola. Accanto a lei, infatti, ci saranno altri supereroi pronti ad affrontare i villains.', new Media(null, 'Film The Marvels'), 4.5, '2023/09/08', '1h 45min'),

    new Movie('Five Nights at Freddy\'s', 'Emma Tammi', ['Josh Hutcherson', 'Matthew Lillard', 'Mary Stuart Masterson'], ['Commedia', 'Horror'], 'USA', 'Universal Pictures', 'Un addetto alla sicurezza deve affrontare delle creature robotiche che entrano in azione di notte.', new Media('FNAF.jpg', 'Film Five Nights at Freddy\'s'), 3.4, '2023/08/27', '1h 50min'),

    new Movie('Cocco di nonna', 'Nicholaus Goossen', ['Linda Cardellini', 'Allen Covert', 'Peter Dante'], ['Commedia'], 'USA', '20th Century Fox', 'Durante il giorno Alex (Allen Covert) testa videogame e fuma spinelli, di notte si dedica allo sviluppo di un nuovo gioco di sua invenzione. Le cose iniziano a complicarsi quando Alex è costretto ad andare a vivere con la nonna Lilly e le sue amiche Grace e Bea. Ai colleghi racconta delle sue nuove inquiline belle e sexy, ma un giorno la nonna e le sue amiche si presentano sul posto di lavoro dove Alex ha già numerosi problemi con J.P., inventore di videogiochi che sembra uscito da una parodia di Matrix e con Samantha, la manager incaricata di seguire l\'ultima fase dello sviluppo de "Lo sterminatore 3" il gioco che dovrà conquistare il mercato.',new Media(null, 'Film Cocco di nonna'), 5, '2006/01/06', '94 min')
];
